name: 'Setup Language Environment'
description: 'Set up the environment for the specified language'
inputs:
  language:
    description: 'The language to set up'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      if: ${{ inputs.language == 'go' }}
      with:
        go-version: '1.20'
    - uses: actions/setup-node@v4
      if: ${{ inputs.language == 'typescript' }}
      with:
        node-version: 18
    - uses: actions/setup-java@v4
      if: ${{ inputs.language == 'java' }}
      with:
        distribution: 'corretto'
        java-version: '17'
    - uses: actions/setup-python@v5
      if: ${{ inputs.language == 'python' }}
      with:
        python-version: '3.10'
    - uses: actions/setup-dotnet@v4
      if: ${{ inputs.language == 'csharp' }}
      with:
        dotnet-version: 8
