name: Build Pull Request

on:
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        language: ['csharp', 'go', 'python', 'java', 'typescript']
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Language Environment
        uses: ./.github/actions/setup-language-env/actions.yml
        with:
          language: ${{ matrix.language }}
          
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: ${{ matrix.language }}/**
          files_ignore: "*.md"
          
      - name: Build changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "::group::Build changes for ${{ matrix.language }}"
          echo ""
          
          changed_files=(${{ steps.changed-files.outputs.all_modified_files }})
          declare -A processed_paths
          
          for file in "${changed_files[@]}"; do
            IFS="/" read path1 path2 extra <<< "$file"
            if [[ $path1 != ${{ matrix.language }} ]]; then
              continue
            fi
            combined_path="$path1/$path2"
            if [[ ${processed_paths[$combined_path]} ]]; then
              continue
            fi
            processed_paths[$combined_path]=1
            
            echo "$combined_path" >> changed_paths.txt
          done
          
          parallel --jobs ${{ matrix.max-parallel }} '
            combined_path="{}"
            
            # Extract the directory path from the combined path
            dir_path="${combined_path%/*}"
            
            # Extract the remaining part of the combined path after the dir_path
            remaining_path="${combined_path#$dir_path/}"
            
            echo "Build Path ${combined_path}"
            
            git clean -dfx
            scripts/build-${{ matrix.language }}.sh "$dir_path" "$remaining_path"
            
            if [[ $? == 0 ]]; then
              echo "- :o: $combined_path"
            else
              echo "- :x: $combined_path"
            fi
          ' :::: changed_paths.txt
          
          echo "::endgroup::"
